### ISSUE TITLE
Adoptability Rating

### ISSUE THREAD

**Issue by kaylarobinson077** [Code-For-Chicago/rescue-chicago#4]

**Comment by kaylarobinson077** [comment]
- [x] Train regression model to predict LOS
- [ ] ~~Standardize LOS output to be a [0,1] as a percentile compared to the training dataset~~
- [x] Save model files somewhere accessible -- maybe save to GitHub?
- [x] Create ticket for deploying the model in the Heroku app

**Comment by JJD129** [comment]
I didn't change the target feature to be between 0-1. Since we decided to do a regression I kept the target as is so it would predict the # of days. I wasn't too sure how we would scale the target to be a % output of adoptability. The model isn't all that accurate and I ended up spending more time trying to retraining the model. In the future if there's a way we can get a binary feature that is [0,1] for adopted vs. not we should consider doing a survival analysis instead of reg.
